### ISSUE TITLE
name could be hamster

### ISSUE THREAD

**Issue by ederag** [extraymond/hamster-snap#1]
In https://github.com/projecthamster/hamster/pull/496#issuecomment-568523325 I recommended `hamster-snap`, with only the github repository name in mind.

https://github.com/extraymond/hamster-snap/blob/52125618778b58ef519fb9c584e7807b400c87c0/snap/snapcraft.yaml#L1

The name could be `hamster`, if you prefer, to state clearly that it is the same application.

**Comment by extraymond** [comment]
Updated now.
