### ISSUE TITLE
use hamster appstream metadata

### ISSUE THREAD

**Issue by ederag** [extraymond/hamster-snap#2]
There are plenty of informations in the [appstream](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) file
https://github.com/projecthamster/hamster/blob/master/data/hamster.metainfo.xml
That could be reused by snap:
https://snapcraft.io/docs/using-external-metadata

**Comment by extraymond** [comment]
It's used now by parsing the hamster.metainfo.xml
